AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS - Windows Node Group (qs-1r15gqid8)
Metadata:
  LintSpellExclude:
    - AWS Systems Manager Parameter Store
    - Linux
    - Windows
    - (Optional)
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - PrivateSubnet3ID
          - NodeSecurityGroup
      - Label:
          default: Amazon EC2 configuration
        Parameters:
          - KeyPairName
          - NodeAmiIdSSMParam
          - CustomAmiId
          - NodeInstanceType
          - NodeVolumeSize
          - BootstrapArguments
      - Label:
          default: EKS configuration
        Parameters:
          - ClusterName
          - NumberOfNodes
          - MaxNumberOfNodes
          - NodeGroupName
          - NodeInstanceProfile
          - NodeInstanceRoleArn
    ParameterLabels:
      PrivateSubnet1ID:
        default: Private Subnet 1 ID
      PrivateSubnet2ID:
        default: Private Subnet 2 ID
      PrivateSubnet3ID:
        default: Private Subnet 3 ID
      NodeSecurityGroup:
        default: Linux node security group
      KeyPairName:
        default: SSH key name
      NodeAmiIdSSMParam:
        default: SSM parameter for Windows AMI ID
      CustomAmiId:
        default: Custom AMI ID
      NodeInstanceType:
        default: Node instance type
      NodeVolumeSize:
        default: Node volume size
      BootstrapArguments:
        default: Arguments to bootstrap script
      ClusterName:
        default: EKS cluster name
      NumberOfNodes:
        default: Number of nodes
      MaxNumberOfNodes:
        default: Maximum number of nodes
      NodeGroupName:
        default: Name of node group
      NodeInstanceProfile:
        default: Node instance profile
      NodeInstanceRoleArn:
        default: Node instance role ARN
Parameters:
  PrivateSubnet1ID:
    Description: ID of private subnet 1 in Availability Zone 1 for the workload (e.g.,
      subnet-a0246123)
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: ID of private subnet 2 in Availability Zone 2 for the workload (e.g.,
      subnet-b1f432cd)
    Type: String
    Default: ""
  PrivateSubnet3ID:
    Description: ID of private subnet 3 in Availability Zone 3 for the workload (e.g.,
      subnet-b1f4a2cd)
    Type: String
    Default: ""
  NodeSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: The security group created for existing worker node groups.
  KeyPairName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Name of an existing EC2 key pair. All instances will launch with
      this key pair.
  NodeAmiIdSSMParam:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Core-EKS_Optimized-1.14/image_id 
    Description: AWS Systems Manager Parameter Store parameter of the default AMI ID for the Windows worker node instances.
  CustomAmiId:
    Type: String
    Default: ""
    Description: (Optional) Specify your own custom AMI ID. This value overrides the AWS Systems Manager Parameter Store value specified above.
  NodeInstanceType:
    Type: String
    Default: m5.large
    AllowedValues: [t3.nano,t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge, m5.large, m5.xlarge, m5.2xlarge,
                    m5.4xlarge, m5.12xlarge, m5.24xlarge, c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge, c5.18xlarge,
                    i3.large, i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge, i3.16xlarge, x1.16xlarge, x1.32xlarge, p3.2xlarge,
                    p3.8xlarge, p3.16xlarge, r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r5.12xlarge, r5.24xlarge, r5d.large, 
                    r5d.xlarge, r5d.2xlarge, r5d.4xlarge, r5d.12xlarge, r5d.24xlarge, z1d.large, z1d.xlarge, z1d.2xlarge,
                    z1d.3xlarge, z1d.6xlarge, z1d.12xlarge]
    ConstraintDescription: Must be a valid EC2 instance type.
    Description: EC2 instance type for the node instances.
  NodeVolumeSize:
    Type: Number
    Default: 50
    Description: Node volume size (should be at least 50 gb).
  BootstrapArguments:
    Type: String
    Default: ""
    Description: "Arguments to pass to the bootstrap script."
  ClusterName:
    Type: String
    Description: The cluster name provided when the cluster was created. If it is incorrect, nodes will not be able to join the cluster.
  NumberOfNodes:
    Default: 3
    Description: Number of EKS node instances.
    Type: Number
  MaxNumberOfNodes:
    Default: ""
    Description: "[OPTIONAL] The maximum number of Amazon EKS node instances, if left blank will be set to the same value as NumberOfNodes."
    Type: String
  NodeGroupName:
    Default: Default-Windows
    Description: Name for EKS node group.
    Type: String
  NodeInstanceProfile:
    Type: String
    Description: ARN for IAM instance profile to attach to nodes.
  NodeInstanceRoleArn:
    Type: String
    Description: IAM role ARN to attach to nodes.

Conditions:
  3AZDeployment: !Not [!Equals [!Ref PrivateSubnet3ID, ""]]
  2AZDeployment: !Or
    - !Not [!Equals [!Ref PrivateSubnet2ID, ""]]
    - !Not [!Equals [!Ref PrivateSubnet3ID, ""]]
  UseCustomAmi: !Not [ !Equals [ !Ref CustomAmiId, "" ] ]
  MaxNodes: !Not [ !Equals [ !Ref MaxNumberOfNodes, "" ] ]
Resources:
  NodeLaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref NodeVolumeSize
            VolumeType: gp2
      IamInstanceProfile: !Ref NodeInstanceProfile
      ImageId: !If
        - UseCustomAmi
        - Ref: CustomAmiId
        - Ref: NodeAmiIdSSMParam
      InstanceType: !Ref NodeInstanceType
      KeyName: !Ref KeyPairName
      SecurityGroups: 
        - !Ref NodeSecurityGroup
      UserData: !Base64
        "Fn::Sub": |
            <powershell>
            [string]$EKSBinDir = "$env:ProgramFiles\Amazon\EKS"
            [string]$EKSBootstrapScriptName = 'Start-EKSBootstrap.ps1'
            [string]$EKSBootstrapScriptFile = "$EKSBinDir\$EKSBootstrapScriptName"
            [string]$cfn_signal = "$env:ProgramFiles\Amazon\cfn-bootstrap\cfn-signal.exe"
            & $EKSBootstrapScriptFile -EKSClusterName ${ClusterName} ${BootstrapArguments} 3>&1 4>&1 5>&1 6>&1
            $LastError = if ($?) { 0 } else { $Error[0].Exception.HResult }
            & $cfn_signal --exit-code=$LastError `
              --stack="${AWS::StackName}" `
              --resource="NodeGroup" `
              --region=${AWS::Region}
            </powershell>

  NodeGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      DesiredCapacity: !Ref NumberOfNodes
      LaunchConfigurationName: !Ref NodeLaunchConfig
      MinSize: !Ref NumberOfNodes
      MaxSize: !If [ MaxNodes, !Ref MaxNumberOfNodes, !Ref NumberOfNodes ]
      VPCZoneIdentifier: !If
        - 3AZDeployment
        - [ !Ref PrivateSubnet1ID, !Ref PrivateSubnet2ID, !Ref PrivateSubnet3ID ]
        - !If
          - 2AZDeployment
          - [ !Ref PrivateSubnet1ID, !Ref PrivateSubnet2ID ]
          - [ !Ref PrivateSubnet1ID ]
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: !Sub ${ClusterName}-${NodeGroupName}-Node
        - Key: !Sub kubernetes.io/cluster/${ClusterName}
          PropagateAtLaunch: true
          Value: owned
        - Key: k8s.io/cluster-autoscaler/enabled
          Value: 'true'
          PropagateAtLaunch: true
        - Key: !Sub 'k8s.io/cluster-autoscaler/${ClusterName}'
          Value: ''
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Count: !Ref NumberOfNodes
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: !Ref NumberOfNodes
        MaxBatchSize: 1
        WaitOnResourceSignals : true
        PauseTime: PT15M

Outputs:
  NodeInstanceRoleArn:
    Description: The node instance role ARN
    Value: !Ref  NodeInstanceRoleArn